import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <nav className="flex justify-between p-4  fixed w-full z-10">
            <div className="font-bold text-2xl ml-[5%]">AWIRUT</div>
            <ul className="flex space-x-6 mr-[3%]"> 
              <Link href='#about'>ABOUT</Link>
              <Link href='#skill' scroll={true}>SKILL</Link>
              <Link href='#project' scroll={true}>PROJECT</Link>
              <Link href='#contect'>CONTECT</Link>

            </ul>
          </nav>
        {children}
      </body>
    </html>
  );
}
